<?xml version="1.0" encoding="utf-8" standalone="yes"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>exceptiondispatchinfo on Always Developing</title><link>https://always-developing.github.io/tags/exceptiondispatchinfo/</link><description>Recent content in exceptiondispatchinfo on Always Developing</description><generator>Hugo -- gohugo.io</generator><language>en-uk</language><lastBuildDate>Thu, 05 May 2022 01:00:00 +0200</lastBuildDate><atom:link href="https://always-developing.github.io/tags/exceptiondispatchinfo/index.xml" rel="self" type="application/rss+xml"/><item><title>Capture exception state</title><link>https://always-developing.github.io/dailydrop/2022/05/05-eventdispatchinfo/</link><pubDate>Thu, 05 May 2022 01:00:00 +0200</pubDate><guid>https://always-developing.github.io/dailydrop/2022/05/05-eventdispatchinfo/</guid><description>Daily Knowledge Drop When catching an exception, the ExceptionDispatchInfo class can be used to capture the state of the exception. This can then later be used to throw the original exception, preserving its original state.
Use case The ExceptionDispatchInfo class is used in the situation where an exception occurs and is caught, but additional processing has to occur before the exception can be thrown up the call stack.
The following examples will clear when and why to use ExceptionDispatchInfo.</description></item></channel></rss>